# Generated by Django 4.1.1 on 2022-09-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="commenet",
            new_name="comment",
        ),
    ]
